### ISSUE TITLE
关于server设置页面新增了ssl的可选项

### ISSUE THREAD

**Issue by nbbcody** [SmileZD/EncryptMinerServer#1]
大神，请问现在如果server设置页面新增的ssl的可选项，填的是否的话，加密是否能生效？
如果要这个ssl选项生效的话，是否要把域名的公钥和秘钥编辑进.js里面?
感谢,现在全套都是用的你的程序

**Comment by SmileZD** [comment]
这个ssl仅限于连接矿池 而client连接服务器不是ssl 所有不需要公钥密钥 现在js里的公钥密钥是用来端对端加密的 不是证书

**Comment by nbbcody** [comment]
好的，感谢🙏
